/**
 * Canonical Growth feature keys only. Zero duplicates.
 * Starter = baseline (no feature checkboxes). Ledger Export + Support Tickets always available.
 * No WhatsApp feature.
 */

export const GROWTH_FEATURE_KEYS = {
  G_CUSTOM_DOMAIN: "G_CUSTOM_DOMAIN",
  G_REMOVE_BRANDING: "G_REMOVE_BRANDING",
  G_ADV_THEME: "G_ADV_THEME",
  G_BANNER_SLIDER: "G_BANNER_SLIDER",
  G_FEATURED_SECTIONS: "G_FEATURED_SECTIONS",
  G_UNLIMITED_PRODUCTS: "G_UNLIMITED_PRODUCTS",
  G_PRODUCT_VARIANTS: "G_PRODUCT_VARIANTS",
  G_BULK_CSV: "G_BULK_CSV",
  G_COUPONS: "G_COUPONS",
  G_ABANDONED_CART_EMAIL: "G_ABANDONED_CART_EMAIL",
  G_ADV_ANALYTICS: "G_ADV_ANALYTICS",
} as const

export type GrowthFeatureKey =
  (typeof GROWTH_FEATURE_KEYS)[keyof typeof GROWTH_FEATURE_KEYS]

export const GROWTH_FEATURE_KEYS_LIST: GrowthFeatureKey[] = [
  GROWTH_FEATURE_KEYS.G_CUSTOM_DOMAIN,
  GROWTH_FEATURE_KEYS.G_REMOVE_BRANDING,
  GROWTH_FEATURE_KEYS.G_ADV_THEME,
  GROWTH_FEATURE_KEYS.G_BANNER_SLIDER,
  GROWTH_FEATURE_KEYS.G_FEATURED_SECTIONS,
  GROWTH_FEATURE_KEYS.G_UNLIMITED_PRODUCTS,
  GROWTH_FEATURE_KEYS.G_PRODUCT_VARIANTS,
  GROWTH_FEATURE_KEYS.G_BULK_CSV,
  GROWTH_FEATURE_KEYS.G_COUPONS,
  GROWTH_FEATURE_KEYS.G_ABANDONED_CART_EMAIL,
  GROWTH_FEATURE_KEYS.G_ADV_ANALYTICS,
]

export type FeatureKey = GrowthFeatureKey

export function isGrowthFeatureKey(key: string): key is GrowthFeatureKey {
  return GROWTH_FEATURE_KEYS_LIST.includes(key as GrowthFeatureKey)
}

export const GROWTH_FEATURES_BY_CATEGORY: Record<string, GrowthFeatureKey[]> = {
  storefront: [
    GROWTH_FEATURE_KEYS.G_CUSTOM_DOMAIN,
    GROWTH_FEATURE_KEYS.G_REMOVE_BRANDING,
    GROWTH_FEATURE_KEYS.G_ADV_THEME,
    GROWTH_FEATURE_KEYS.G_BANNER_SLIDER,
    GROWTH_FEATURE_KEYS.G_FEATURED_SECTIONS,
  ],
  catalog: [
    GROWTH_FEATURE_KEYS.G_UNLIMITED_PRODUCTS,
    GROWTH_FEATURE_KEYS.G_PRODUCT_VARIANTS,
    GROWTH_FEATURE_KEYS.G_BULK_CSV,
  ],
  marketing: [
    GROWTH_FEATURE_KEYS.G_COUPONS,
    GROWTH_FEATURE_KEYS.G_ABANDONED_CART_EMAIL,
  ],
  analytics: [GROWTH_FEATURE_KEYS.G_ADV_ANALYTICS],
}
